### ISSUE TITLE
SyntaxError: Unexpected token punc «)»

### ISSUE THREAD

**Issue by zpwebbear** [KarboniteKream/vue-momentjs#1]
ERROR in static/js/vendor.9d36f5eb05df163409d5.js from UglifyJs
SyntaxError: Unexpected token punc «)», expected punc «(» [./~/vue-momentjs/index.js:12,0]
If this part of code 
```
$moment: {
				get() {
					return moment;
				}
			},
```
rewrite this way
```
$moment: {
				get: function() {
					return moment;
				}
			},
```
there will be no errors

**Comment by KarboniteKream** [comment]
This has been fixed, thanks for reporting!

It seems this was an issue with an older version of UglifyJS which doesn't support ES6. But nevertheless, a small library like this should use ES5 syntax for better compatibility.
